Menu entry changed for ghns and scanner installer and scanner now can convert into pdf

diff --git a/kde-services-menu/kde-service-menu-scanner/install b/kde-services-menu/kde-service-menu-scanner/install
--- a/kde-services-menu/kde-service-menu-scanner/install
+++ b/kde-services-menu/kde-service-menu-scanner/install
@@ -1,4 +1,4 @@
-#!/bin/bash -x
+#!/bin/bash
 ##license gpl 
 #This program is free software: you can redistribute it and/or modify
 #it under the terms of the GNU General Public License as published by
@@ -17,11 +17,6 @@
 
  
 
-bin="/usr/local/bin/"
-folder_local_bash_scripts="$HOME/bin"
-prefix="$(kde4-config --prefix)"
-localprefix="$(kde4-config --localprefix)"
-
 
 function_check_folder_and_create_it_if_doesnt_exist () {
 	if [[ ! -d "$1" ]]; then 
@@ -30,7 +25,7 @@ function_check_folder_and_create_it_if_doesnt_exist () {
 		
 		mkdir "$1"
 	else
-		echo $"			Folder $1 exist 
+		echo $"..............Folder $1 exist 
 		"
 	fi 
 	
@@ -48,61 +43,90 @@ fi
 
 function_systemwide() {
 
-sudoerror=false
-pas=$(kdialog --password $"Insert Root Password $wrongpas")
-
-
-if [[ -z "$pas" ]];then
-kdialog --error $"No password give exiting..."
-exit  
-fi
-
- 
-#install every script with the correct permission
- for file in $PWD/usr/bin/* ; do
-	 echo "installing..... sudo -S  install -m 755 -D "$file"  "/usr/local/bin""
-	echo "$pas" | sudo -S  install -m 755 -D "$file"  "/usr/local/bin" 2>/dev/null 
-
- #wtf need to fix this shit very ugly xD
-	if [[ $? ==  1 ]]; then
-	sudoerror=true
-	else 
 	sudoerror=false
+	pas=$(kdialog --password $"Insert Root Password $wrongpas" 2>/dev/null )
+	
+	
+	if [[ -z "$pas" ]];then
+		kdialog --error $"No password given exiting..." 2>/dev/null 
+		exit  
 	fi
-  done
-
-  function_checksudo
+		
+		
+		#install every script with the correct permission
+		directory="$PWD/usr/bin/"
+		if [[  -d "$directory"  ]] ; then
+			for file in $PWD/usr/bin/* ; do
+				echo "installing..... sudo -S  install -m 755 -D "$file"  "/usr/local/bin""
+				echo "$pas" | sudo -S  install -m 755 -D "$file"  "/usr/local/bin" 2>/dev/null 
+				
+				#wtf need to fix this shit very ugly xD
+				if [[ $? ==  1 ]]; then
+					sudoerror=true
+				else 
+					sudoerror=false
+				fi
+			done
+		else
+			echo "directory $directory  doens't exit  skipping"
+		fi 
+							
+							
+							
+	function_checksudo
 
 
 #install the service menu 
-  
-   for file in $PWD/usr/share/kde4/services/ServiceMenus/*.desktop;  do
-	   echo "installing..... sudo -S install -m 644 -D "$file"  ""$prefix"/share/kde4/services/ServiceMenus""
-	   echo "$pas" | sudo -S install -m 644 -D "$file"  ""$prefix"/share/kde4/services/ServiceMenus" 
-  done
+	directory="$PWD/usr/share/kde4/services/ServiceMenus/"
+	if [[  -d "$directory"  ]] ; then 
+		for file in $PWD/usr/share/kde4/services/ServiceMenus/*.desktop;  do
+			echo "installing..... sudo -S install -m 644 -D "$file"  ""$prefix"/share/kde4/services/ServiceMenus""
+			echo "$pas" | sudo -S install -m 644 -D "$file"  ""$prefix"/share/kde4/services/ServiceMenus" 
+		done
+	else
+		echo "directory $directory doesn't exit skipping "
+	fi
+#install menu entry 
 
-  #install menu entry 
-if [[ -d "$PWD/usr/share/applications/kde4/" ]]; then 
-	echo "$PWD/usr/share/applications/kde4/  detected "
- 
-  for file in $PWD/usr/share/applications/kde4/*.desktop ; do 
-	  echo "installing..... sudo -S install -m 755 -D "$file"  ""$prefix"/share/applications/kde4/""
-	  echo "$pas" | sudo -S install -m 755 -D "$file"  ""$prefix"/share/applications/kde4/" 
-done 
-
-fi 
+	directory="$PWD/usr/share/kde4/services/ServiceMenus/"
+	if [[  -d "$directory"  ]] ; then 
+		if [[ -d "$PWD/usr/share/applications/kde4/" ]]; then 
+			echo "$PWD/usr/share/applications/kde4/  detected "
+			
+			for file in $PWD/usr/share/applications/kde4/*.desktop ; do 
+				echo "installing..... sudo -S install -m 755 -D "$file"  ""$prefix"/share/applications/kde4/""
+				echo "$pas" | sudo -S install -m 755 -D "$file"  ""$prefix"/share/applications/kde4/" 
+			done 
+				
+		fi 
+	else
+		echo "directory $directory doesn't exit skipping "
+	fi 
 
 # echo  "running .....kbuildsycoca4  update service menus... wait.."
 echo 
 echo 
- kbuildsycoca4  # echo "$pas" | sudo -S -u $SUDO_USER #GET  kbuildsycoca4 running like normal user ..to avoid error message
+ kbuildsycoca4 2>/tmp/servicemenubashinstaller.log  # echo "$pas" | sudo -S -u $SUDO_USER #GET  kbuildsycoca4 running like normal user ..to avoid error message
 echo
-echo "END! EVERYTHING DONE!"
-
+echo $"END! EVERYTHING DONE!"
+kdialog --passivepopup $"$PWD Service Menu Installed.. bye" 2 2>/dev/null
  
- 
+#reset password 
 pas=""
- }
+
+if [[ -e "$PWD/extra_bash_function_installation" ]]; then 
+	if [[ $(declare -F function_extra_install_global ) ]]; then 
+		echo $"Wide Function Extra Install Global"
+		function_extra_install_global	
+	elif [[ $(declare -F function_extra_install_wide )  ]]; then 
+		echo "Wide Install Extra function Detected executing.."
+		function_extra_install_wide
+	else 
+		echo $"No Extra wide Install functions"
+	fi 
+
+fi 
+}
 
 function_local(){
 
@@ -131,7 +155,7 @@ if  [[ -z $(echo "$PATH"| grep  "$folder_local_bash_scripts") ]]; then
 
 else
 	echo
-	echo $"$folder_local_bash_scripts already on path ...skipping"
+	echo $"..............$folder_local_bash_scripts already on path ...skipping"
 	echo
 fi 
 
@@ -141,7 +165,7 @@ fi
 
 #install every script with the correct permission
 	for file in $PWD/usr/bin/* ; do
-		echo "installing..... install -m 755 -D "$file"  "$folder_local_bash_scripts""
+		echo "..............install -m 755 -D "$file"  "$folder_local_bash_scripts""
 		install -m 755 -D "$file"  "$folder_local_bash_scripts" 
 	done
 
@@ -165,10 +189,24 @@ fi
 		done
 	fi 
 
-	kbuildsycoca4
+	kbuildsycoca4 2>/tmp/servicemenubashinstaller.log
 
-	kdialog --passivepopup $"$PWD Service Menu Installed.. bye" 2
-	kdialog --msgbox $"if you can't launche the program Please login and logout , this should load the new bash_profile"
+	kdialog --passivepopup $"$PWD Service Menu Installed.. bye" 2 2>/dev/null
+	kdialog --msgbox $"if you can't launch the program Please login and logout , this should load the new bash_profile" 2>/dev/null
+	
+	if [[ -e "$PWD/extra_bash_function_installation" ]]; then 
+		if [[  $(declare -F function_extra_install_global )  ]]; then
+			echo "Global extra function Detected Executing.."
+			function_extra_install_global
+		elif [[ $(declare -F function_extra_install_local ) ]]; then 
+			echo "Local Install Extra function Detected executing.."
+			function_extra_install_local
+		else 
+			echo $"No Extra local Install functions"
+		fi 
+
+	fi 
+ 
 }
 
 
@@ -220,9 +258,22 @@ if [[ -d "$PWD/usr/share/applications/kde4/" ]]; then
 fi 
  
 ####################################################################
-kbuildsycoca4
-kdialog --passivepopup $"Removed these files  $messageremoved" 2
+kbuildsycoca4 2>/tmp/servicemenubashinstaller.log
+kdialog --passivepopup $"Removed these files  $messageremoved" 2 2>/dev/null
 
+if [[ -e "$PWD/extra_bash_function_deinstallation" ]]; then 
+	
+	if [[ $(declare -F function_extra_deinstall_global )  ]]; then 
+		echo $"Function extra deinstall global detected executing"
+		function_extra_deinstall_global
+	elif [[ $(declare -F function_extra_deinstall_local )   ]]; then 
+		echo $"Function extra deinstall local detected executing"
+		function_extra_deinstall_local
+	else 
+		echo $"No Function extra deinstall detected"
+	fi 
+
+fi 
 
 
 }
@@ -232,11 +283,11 @@ function_remove_system(){
 
 messageremoved=""
 sudoerror=false
-pas=$(kdialog --password $"Insert Root Password $wrongpas")
+pas=$(kdialog --password $"Insert Root Password $wrongpas" 2>/dev/null)
 
 
 if [[ -z "$pas" ]];then
-kdialog --error $"No password give exiting..."
+kdialog --error $"No password give exiting..." 2>/dev/null
 exit  
 fi
 
@@ -247,7 +298,7 @@ file="${file##*/}"
 # file="${file%%.*}"
  
 	if [[ -e "/usr/local/bin/$file"  ]]; then
-	echo $" rm   "/usr/local/bin/$file""
+	echo $"rm   "/usr/local/bin/$file""
 	echo "$pas" | sudo -S rm   "/usr/local/bin/$file" 
 	messageremoved="$messageremoved /usr/local/bin/$file"
 	else 
@@ -284,16 +335,28 @@ if [[ -d "$PWD/usr/share/applications/kde4/" ]]; then
 			
 fi 
 			
-  kbuildsycoca4
-kdialog --passivepopup $"Removed these files  $messageremoved"
+kbuildsycoca4 2>/tmp/servicemenubashinstaller.log
+kdialog --passivepopup $"Removed these files  $messageremoved" 2>/dev/null
   
+if [[ -e "$PWD/extra_bash_function_deinstallation" ]]; then 
+	
+	if [[ $(declare -F function_extra_deinstall_global )  ]]; then 
+		echo $"Function extra deinstall global detected executing"
+		function_extra_deinstall_global
+	elif [[ $(declare -F function_extra_deinstall_wide ) ]]; then 
+		echo $"Function extra deinstall wide detected executing"
+		function_extra_deinstall_wide
+	else
+		echo $"No Function extra deinstall wide detected"
+	fi 
 
+fi 
 }
 
 function_main(){
  
-answer=$(kdialog  --title $"Service menu installation menu " --menu  $"Installation Menu: choose an installation option"  l  $"Local Installation"  sw $"System Wide Installation" neutral "*******************" r $"Remove Local" rs $"Remove System wide" --default "Local Installation" )
-
+answer=$(kdialog  --title $"Service menu installation menu " --menu  $"Installation Menu: choose an installation option"  l  $"Local Installation"  sw $"System  Installation" neutral "**********************************************" r $"Remove Service Menu Locally" rs $"Remove Service Menu from the System" --default "Local Installation" 2>/dev/null)
+echo "menu entry $answer"
 case $answer in 
 
 l)
@@ -323,6 +386,27 @@ esac
 }
 
 
+bin="/usr/local/bin/"
+folder_local_bash_scripts="$HOME/bin"
+prefix="$(kde4-config --prefix)"
+localprefix="$(kde4-config --localprefix)"
+
+#import extra function from other files if they exit 
+if [[ -e "$PWD/extra_bash_function_installation" ]]; then 
+	echo $"Extra installation file detected loading functions
+. $PWD/extra_bash_function_installation"
+
+. "$PWD/extra_bash_function_installation"  
+elif [[ -e "$PWD/extra_bash_function_deinstallation" ]]; then 
+	echo $"Extra deinstallation file detected loading functions
+. $PWD/extra_bash_function_deinstallation"
+
+. "$PWD/extra_bash_function_deinstallation" 
+fi 
+
+
+
+
 echo "
 PARAMETERS:
 
@@ -332,5 +416,4 @@ prefix: $prefix
 local prefix: $localprefix
 
 "
-
 function_main
